controllers:
    resource: ../../src/Controller/
    type: annotation

crud_controllers:
    resource: ../../src/Controller/Crud/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
